RsyncProject/rsync

cleanup.c, io.c, rsync.h
Hi,
Here is a PR which sends last error messages to sender for a file-transfer which failed.
It helps especially with protocol < 31.
This can be useful for example to know that a FS is full.
Many thanks 👍
```
/repository/mybigfile.iso
539.26M   6%   11.21MB/s    0:11:01  
rsync: [sender] write error: Broken pipe (32)
rsync error: error in file IO (code 11) at io.c(831) [sender=3.1.2]
/repository/mybigfile.iso
539.26M   6%   11.21MB/s    0:11:01  
rsync: write failed on "/repository/mybigfile.iso" (in bkp): Disc quota exceeded (69)
rsync error: error in file IO (code 11) at receiver.c(400) [receiver=3.1.2]
rsync error: error in file IO (code 11) at io.c(1633) [generator=3.1.2]
rsync: [sender] write error: Broken pipe (32)
rsync error: error in file IO (code 11) at io.c(831) [sender=3.1.2] …
```
=> Correctly send last error to sender

log.c
Hi,
This PR allows the daemon to log data sent/received even in case of error, which can be interesting to have when the transfer has been interrupted by the client.
Many thanks 👍
_Initial report [there](https://bugzilla.samba.org/show_bug.cgi?id=12838), pushed here by convenience._
=> Log data sent/received even if error

COPYING
Add the OpenSSL license exception also to the COPYING file which
contains the license related information.
Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
=> Add OpenSSL license exception also to COPYING

packaging/systemd/rsync.service, packaging/systemd/rsync.socket, packaging/systemd/rsync@.service
Note this does limit rsync via systemd - it's a trade off for security.
With these units system (with some exceptions) is read-only, users' homes and devices are hidden. Comments give a hint how to undo this.
=> enhance and add systemd units

configure.ac, simd-checksum-x86_64.cpp
configure.ac was modified to detect g++ 5+ and clang++ 7+. Additionally
some script malfunctions on FreeBSD were corrected.
The get_checksum1() code has been modified to fix clang and g++ 10
compilation.
This version of the code and configure.ac has been tested on:
Ubuntu 16 - gcc 7.3.0, clang 6.0.0
Debian 10 - gcc 5.4.0, 6.4.0, 7.2.0, 8.4.0, 9.2.1, 10.0.1, clang 5.0.2,
6.0.1, 7.0.1, 8.0.0, 9.0.0, 10.0.0
ArchLinux 20200605 - gcc 10.1.0, clang 10.0.0
FreeBSD 12.1 - gcc 9.3.0, clang 8.0.1
It is unknown if it will work on gcc 5.0-5.3, but the script currently
allows it.
=> x86-64 SIMD build fixes

Makefile.in, lib/sysxattrs.h
xattr headers have been provided by glibc (at least on Linux/glibc) for many years now.
Reorder the inclusion of xattr headers to attempt compatibility/legacy after the common case.
This prevents the warning without changing compatibility to old/non-glibc systems.
=> Prevent unnecessary xattr warning by reordering header inclusion.

lib/md5-asm-x86_64.s
The Mach-O x86-64 model doesn't seem to support `.type` and `.size` directives in assembly. Add ifdefs that should allow for the file to build without issues in Apple Clang.
See also:
- https://github.com/micropython/micropython/pull/73
- https://stackoverflow.com/a/19725269
=> lib/md5-asm-x86_64.s: fix build with Apple Clang

options.c, rsync.1.md
Hello Wayne,
I'm sending this patch we currently apply in the Debian packaging of rsync, I believe it would be nice to have it upstreamed.
Thanks,
=> Make --backup be set when --backup-dir is used

Makefile.in
When building out of source tree, we can't find rsync-ssl in the current
directory and installation fails.  Fix it by using the srcdir variable for the
path to rsync-ssl.
Signed-off-by: Hiroshi Takekawa <sian.ht@gmail.com>
=> Makefile.in: Use srcdir for installing rsync-ssl

rsyncd.conf.5.md
All nginx configuration directives end in semicolon.
=> Add missing semicolon in man page

clientserver.c, daemon-parm.txt, rsyncd.conf.5.md
I think it's pretty useful to tell an rsync daemon to also use A_NOATIME when opening files. This should do it.
paul@debian.org
=> Add "open noatime" module option to rsyncd.conf

.cirrus.yml
Hi,
This is a very first version of a FreeBSD CI.
It's based on Cirrus CI : https://cirrus-ci.org
Used in other projects, it works perfectly.
Once we have this build properly working, goal is then to include tests, as in the Linux CI.
You should then have to enable Cirrus CI on this repository Wayne, if you're OK to go further with this.
Many thanks 👍
=> Add FreeBSD CI

.cirrus.yml, runtests.sh, testsuite/chown.test, testsuite/devices.test, testsuite/xattrs.test
Hi,
Let's try to improve FreeBSD tests :
- mute the `acl_get_file() failed: Operation not supported` errors in non-acl tests ;
- use the correct attr commands in tests using them ;
- create a ZFS pool and mount it on `testtmp` dir, so that tests will run in this dedicated FS, which then makes `chmod-temp-dir` to run, as well as `dir-sgid` (on UFS, sticky bit is not inherited, whereas it is on ZFS).
Thx 👍
=> Improve FreeBSD tests

.cirrus.yml
Hi,
I re-enabled `rsync-ssl` test in FreeBSD CI, as `bash` is already built-in.
Thx 👍
=> Enable FreeBSD CI ssl

.gitattributes
Hi,
If we want to build a Windows/Cygwin CI, we'll need to tell git not to transform line endings.
I simply forgot it in #67, while I clearly needed it in other projects' Cygwin CI.
Sounds like you also faced the `\r` issue in some of your CI tests @WayneD.
This will then help.
Ben
=> Force git line endings

simd-checksum-x86_64.cpp
Hi, i was playing around with the avx2 enabled checksum function and noticed that you could reduce the number of shuffles needed if you interleave the data inside the ymm registers. Basically we do two 128bit lanes in parallel and merge the result at the end, instead of using the full 256bit registers as a single vector. The code is based on the SSSE3 one, with small tweaks to reduce the number of immediate that need to be loaded from memory.
I've run the embedded benchmark and the AVX2 codepath went from ~12GB/s to ~14.8GB/s on and Intel 6700k. 
The checksum in the benchmark matches that of the other implementations so hopefully the algorithm is equivalent, but i've only tested it on linux-x86_64 with gcc 10.
=> optimize avx2 codepath

configure.ac
Good day
I found couple of issues when I tried to use the lastest rsync release with buildroot.
1. x86 asm is used even in case of cross-compilation to non-x86 arch;
2. x86 SIMD code is used  in case of cross-compilation to non-x86 arch.
I see the patch in the trunk which addresses the second issue, but it completely disables SIMD with cross-compilation.
Please review my patches.
=> Small cross-compilation fixes

configure.ac
The current GLIBC check does not consider we may see glibc 3.0 in the future.
It almost feels criminal submitting a very tiny PR like this, but it bothered me!
=> Updated GLIBC check in configure.ac

rsync-ssl
otherwise openssl will give an error and not accept is as argument
=> add missing - in certopt

configure.ac
Test IPv6 compatibility directly instead of relying on library probes.
Legacy configure behaviour was to detect IPv6 support through known IPv6
capable version of common standard libraries. Now: it runs a POSIX test
to determine if IPv6 is usable (in case it has not been disabled).
Patch originally from Pierre-Olivier Mercier <nemunaire@nemunai.re>.
Tested on Gentoo/musl where IPv6 does not otherwise work.
Signed-off-by: Jonathan Davies <jpds@protonmail.com>
=> configure.ac: Test IPv6 compatibility directly

xattrs.c
When we need to set extended atributes of file which does not
allow write then temporarily add write permission and after
attributes are set, remove it again.
Resolves #208
=> Eventually add write permission when setting extended attributes

rsync-ssl, rsync-ssl.1.md
as discussed [here](https://github.com/WayneD/rsync/issues/211) this PR adds an option to provide a key file to rsync-ssl
=> add ssl/tls key option

flist.c, rsync.h
In 2004, an allocation optimization has been added to the file
list handling code, that preallocates 32k of file_struct pointers
in a file_list. This optimization predates the incremental
recursion feature, for which it is not appropriate anymore. When
copying a tree containing a large number of small directories,
using the incremental recursion, rsync allocates many short
file_lists. Suddenly, the unused file_struct pointers can easily
take 90-95% of the memory allocated by rsync.
This can be easily reproduced by using
valgrind --tool=massif ./rsync -anx /usr /tmp/
and checking the memory profile of the first (sender) process.
This patch changes the flist functions to start only with 32 entries
for the partial file lists, instead of 32 * 1024.
It also modifies the condition for the debug …
=> Reduce memory usage

Makefile.in, configure.ac, install-sh, packaging/prep-auto-dir, prepare-source, runtests.sh, testsuite/chmod-temp-dir.test, testsuite/rsync.fns
I faced `test: too many arguments` when building using [sbase](https://core.suckless.org/sbase/).
This is due to a non-POSIX syntax `test ... -a ...` and `test … -o …`.
> The XSI extensions specifying the -a and -o binary primaries and the '(' and ')' operators have been marked obsolescent.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html
=> shell: test -a|o is not POSIX

configure.ac
Hello, thank you for fixing cross compilation issues. We need just one [quick improvement for cross compilation detection](https://bugs.gentoo.org/732084).
```
$host = x86_64-pc-linux-gnu
$build = x86_64-unknown-linux-gnu
```
This configuration means cross compilation, so I can suggest comparison just between `$host` and `$build`.
=> configure.sh:4912: checking whether to enable SIMD optimizations // configure.sh:4936: error: cannot run test program while cross compiling

support/rrsync
Fix an off-by-one in the `args.dir_slash_len` variable that leads to base every absolute path on `/`
=> Fix rrsync directory normalization

io.c
stop-at, stop-after and time-limit options must be transfer
direction agnostic, and must apply to rsync in receiver
or sender mode.
=> Time limit options applies to send and receive transfers

rsync.1.md
Fix wording from 'does is not read' -> 'is not read'
=> Fix wording in RSYNC_PORT section

testsuite/copy-file-inplace.test, testsuite/copy-file.test, util1.c
Extract static function unlink_and_reopen() from copy_file()
I confess that the primary purpose of this pull request is to
remove the assignment to function argument `ofd` of `copy_file()`.
I believe renaming argument `ofd` to `tmpfilefd` clarifies that 
in normal use, `copy_file()` will unlink and re-create `dest`;
and that passing a value >=0 for `tmpfilefd` is the exceptional case.
I believe there are no side-effects of this extraction, by static analysis.
Specifically: `mode` is modified in the extracted code, but because `mode`
is never read again after its use in `do_open()`, this has no downstream effect.
Extracting the function `unlink_and_reopen()` splits the error handling
between the new function, which now reports the errors, and `copy_file()`
which still calls `close(ifd)` to …
=> Extract unlink_and_reopen from copy_file

zlib/deflate.c, zlib/deflate.h, zlib/trees.c
A CVE was found in zlib that was introduced in zlib-1.2.2.2 and affects every version released after that including the bundled version in rsync. I've used the original patch with one or two small changes where it would not fit the bundled version.
Adding the zlib upstream fix here, the detailed explanation is in the commit - https://github.com/madler/zlib/commit/5c44459c3b28a9bd3283aaceab7c615f8020c531
=> Fix for CVE-2018-25032 in zlib

support/git-set-file-times
Solve the following problems with support/git-set-file-times:
* mishandling of commit message lines similar to committer lines
* UnicodeDecodeError with commit messages that cannot be interpreted
as utf-8
```
$ mkdir repo
$ cd repo
$ git init
$ touch README
$ git add README
$ git commit -m "committer foo 0 +0000"
$ ls -l README
-rw-rw-r-- 1 vagrant vagrant 0 Apr  3 11:39 README
$ git set-file-times
Setting README
$ ls -l README
-rw-rw-r-- 1 vagrant vagrant 0 Jan  1  1970 README
```
```
$ git clone https://github.com/git/git
$ cd git
$ git set-file-times
...
Setting t/t3900/ISO-2022-JP.txt
Setting t/t3900/1-UTF-8.txt
Setting t/t3900/2-UTF-8.txt
Setting compat/strlcpy.c
Traceback (most recent call last):
File "/vagrant/git-set-file-times", line 92, in <module>
main()
File …
```
=> Avoid malfunctions and unexpected errors with git-set-file-times

packaging/systemd/rsync.service
man 5 systemd.service:
> Setting this to on-failure is the recommended choice for long-running services
Partial fix for https://bugzilla.samba.org/show_bug.cgi?id=13463
=> systemd: restart daemon on-failure

rsync.1.md
Typos caught on Debian when packaging the latest release (3.2.5).
Thank you
=> Fix typos on manpage

exclude.c
Fortified (`-D_FORTIFY_SOURCE=2` for gcc) builds make `strlcpy()` crash when its third parameter (size) is larger than the buffer:
```
$ rsync -FFXHav '--filter=merge global-rsync-filter' Align-37-43/ xxx
sending incremental file list
*** buffer overflow detected ***: terminated
```
It's in the exclude code in `setup_merge_file()`:
```
strlcpy(y, save, MAXPATHLEN);
```
Note the `y` pointer was incremented, so it no longer points to memory with `MAXPATHLEN` "owned" bytes.
Fix it by remembering the number of copied bytes into the `save` buffer and use that instead of `MAXPATHLEN` which is clearly incorrect.
Fixes #511.
=> exclude: fix crashes with fortified strlcpy()

configure.ac
Fixing this warning escalated to an error, resuting in no IPv6 support:
```
configure.sh:7679: checking whether to enable ipv6
configure.sh:7718: clang -o conftest -g -O2 -DHAVE_CONFIG_H -Wall -W   conftest.c  >&5
conftest.c:73:1: error: type specifier missing, defaults to 'int'; ISO C99 and later do not support implicit int [-Wimplicit-int]
main()
^
int
1 error generated.
configure.sh:7718: $? = 1
configure.sh: program exited with status 1
```
=> configure.ac: fix failing IPv6 check due to missing return type

acls.c
recv_ida_entries still needs to be called regardless, so we cannot take that out. Let's just quiet the compiler instead.
=> Silence unused var warning

Makefile.in, configure.ac, popt/lookup3.c, popt/popt.c, popt/popt.h, popt/poptconfig.c, popt/popthelp.c, popt/poptint.c, popt/poptint.h, popt/poptparse.c, popt/system.h
fixes https://github.com/RsyncProject/rsync/issues/589
=> update to popt 1.19

.github/workflows/solaris-build.yml
Since we're building with `-disable-zstd --disable-xxhash --disable-lz4`, I'm not installing the following packages:
* `devel/xxhash`
* `zstd`
* `liblz4`
* `archivers/liblz4`
=> CI: added Solaris build

INSTALL.md
I added some notes for under macos for the install.md to make it a bit more clear how to link libraries for m series macs due to the new non standard install location of homebrew packages.
=> Apple silicon linker path details

acls.c
When sizeof(mode_t) != sizeof(int) it will result in unintentional reads of global memory as shown when running the tests with sanitizers:
```
==31861==ERROR: AddressSanitizer: global-buffer-overflow on address 0x00010b7e3240 at pc 0x00010b5f192f bp 0x7ff7b4a3d6b0 sp 0x7ff7b4a3d6a8
READ of size 4 at 0x00010b7e3240 thread T0
#0 0x10b5f192e in default_perms_for_dir acls.c:1093
#1 0x10b503332 in recv_generator generator.c:1339
#2 0x10b50d8a9 in generate_files generator.c:2293
#3 0x10b554ecb in do_recv main.c:1114
#4 0x10b54ee66 in start_server main.c:1261
#5 0x10b54e2f3 in child_main main.c:1234
#6 0x10b605877 in local_child pipe.c:166
#7 0x10b558a26 in start_client main.c:1577
#8 0x10b556cce in main main.c:1848
#9 0x7ff816f15365 in start+0x795 (dyld:x86_64+0xfffffffffff5c365)
0x00010b7e3240 …
```
=> acls: sync type for orig_umask and clear macOS compilation warnings

lib/pool_alloc.c, simd-checksum-x86_64.cpp, syscall.c
These warnings may seem benign but will soon turn into compilation errors, starting with clang-17 and gcc-14. I tried hard to find a use for the duplicated (and incorrect) lseek prototypes, but could not find any.
The alignment issue was also flagged by clang. I'm not a SIMD expert but explicit 1-byte aligment for a vector seems wrong.
With these fixes rsync itself is now 100% warning-free :)
=> Fix misc. warnings found by clang-16

support/rrsync.1.md
Replace ¨rw¨ with ¨ro¨.
Reported on Debian by Adriano Rafael Gomes <adrianorg@debian.org>
=> rrsync: fix wrong parameter name in manpage SYNOPSIS

lib/pool_alloc.c
This is more intuitive than adding a negative number.
=> Introduce PTR_SUB

support/rrsync
rsbackup (https://github.com/ewxrjk/rsbackup) uses `ssh <host> true` to check that the host in question is reachable.  I like to configure my backed-up hosts to force the backup system to go via `rrsync`, but I always have to add a local tweak to allow `SSH_ORIGINAL_COMMAND=true` to work.  I think this would be safe enough to include in rrsync.
=> Allow basic connectivity check via rrsync

configure.ac
This prevents "undefined symbol" errors which might arise from libcrypto.a if linking openssl statically.
This happens to me as:
- I build my own zlib, which is a recent one (1.31)
- build my own OpenSSL against the above zlib
- everything is link statically
- I configure rsync with `--with-included-zlib=no`.
With this configuration, rsync fails to link with errors like:
```
gcc -std=gnu11 -I/workdir/src/rsync-3.2.7/popt -O2 -mmmx -msse -msse2 -msse3 -I/opt/1A/toolchain/x86_64-2.6.32-v2.0.102/build-pack/2.0.102.0/include -I/workdir/build/x86_64/build-pack/build-pack-temporary-static-dependencies/install/include -I/workdir/build/x86_64/build-pack/build-pack-temporary-static-dependencies/install/include/ncurses -I/opt/1A/toolchain/x86_64-2.6.32-v2.0.102/build-pack/2.0.102.0/internal-python-o …
```
=> When not using the builtin zlib, link it before linking libcrypto, as libcrypto depends on zlib.

hlink.c
~1. Suppress -Wold-style-definition warnings globally since we prefer old-style definitions.~
2. Fix hlink.c's cast in qsort() call to properly declare type.
~3. Fix pool_alloc.c's function pointer type to match its usage.~
~4. Fix syscall.c's lseek64 forward declarations.~
~5. Fix bool typedef conflict in wildtest.c by renaming to rsync_bool.~
This cleans up the build with modern compilers (GCC15) while maintaining compatibility with older versions. The qsort comparison function cast in particular is now more type-safe.
Closes #664
=> GCC15(-std=gnu23) adjustment: Fix function pointer cast in qsort()

NEWS.md, checksum.c, flist.c, generator.c, match.c, receiver.c, rsync.h, sender.c, syscall.c, t_unsafe.c, testsuite/safe-links.test, testsuite/unsafe-byname.test, tls.c, trimslash.c, util1.c, version.h
This prepares for the release of 3.4.0, which is a security release coordinated with CERT and VINCE
See https://kb.cert.org/vuls/id/952657
=> release 3.4.0

rsync.h
fixes commit 688f5c379a43 (Refuse a duplicate dirlist.)
Fixes: https://github.com/RsyncProject/rsync/issues/702
Fixes: https://github.com/RsyncProject/rsync/issues/697
=> Fix FLAG_GOT_DIR_FLIST collission with FLAG_HLINKED

generator.c
full_fname() will free the return value in the next call so we need to duplicate it before passing it to rsyserr.
Fixes: https://github.com/RsyncProject/rsync/issues/704
=> Fix use-after-free in generator

testsuite/hardlinks.test
https://github.com/RsyncProject/rsync/issues/702
=> Simple test to validate -H break reported in #702

syscall.c
Fixes: https://github.com/RsyncProject/rsync/issues/701
=> Fix build on ancient glibc without openat(AT_FDCWD

popt/findme.c
fixes build on systems without alloca, such as NonStop ia64
=> popt: remove dependency on alloca

popt/findme.c
it treats missing prototype as an error, not warning
=> fixed build error on ia64 NonStop
